---

git_repo: https://github.com/monty5811/apostello.git
git_version: v2.5.1

project_name: apostello
application_name: apostello

# Database settings.
db_user: "{{ application_name }}"
db_name: "{{ application_name }}"

# Gunicorn settings. For the number of workers, a good rule to follow is
# 2 x number of CPUs + 1
gunicorn_num_workers: 3

# Setting this to 1 will restart the Gunicorn process each time
# you make a request, basically reloading the code. Very handy
# when developing. Set to 0 for unlimited requests (default).
gunicorn_max_requests: 0

# Application settings.
django_settings_file: settings.production
