---
# Let's Encrypt (free SSL):
le_email: ""
# Database settings
db_password: "this should be changed to a long random string"
# Nginx settings
nginx_server_name: "_" # replace this with your domain name
# Application Settings
django_secret_key: 'this should be a very long string'
# this is used in the account related emails and should match your server settings
account_default_http_protocol: 'https'
# Whitelisted domains
whitelisted_login_domains:
# locale and time zone:
django_time_zone: 'Europe/London' # change me
# Elvanto
elvanto_key:
country_code:
# rollbar
rollbar_access_token: ''
rollbar_access_token_client: ''
# Cloud messaging
cm_server_key:
cm_sender_id:
