---
# Database settings
db_password: test
# Nginx settings
nginx_server_name: 127.0.0.1
# Application Settings
django_secret_key: 'this should be a very long string'
# this is used in the account related emails and should match your server settings
account_default_http_protocol: 'https'
# Whitelisted domains
whitelisted_login_domains: ''
# locale and time zone:
django_time_zone: 'Europe/London'
# Elvanto
elvanto_key: '00000000000000000000000000000000'
country_code: 44
# Rollbar
rollbar_access_token: ''
rollbar_access_token_client: ''
# Cloud messaging
cm_server_key: ''
cm_sender_id: ''
