language: python
python:
  - "3.4"
  - "3.5"
env:
  global:
    - DJANGO_SETTINGS_MODULE=settings.test
    - DJANGO_EMAIL_HOST=not_used_in_tests
    - DJANGO_EMAIL_HOST_USER=not_used_in_tests
    - DJANGO_EMAIL_HOST_PASSWORD=not_used_in_tests
    - SLACK_URL=''
    - FROM_EMAIL=noreply@example.com
install: "pip install -r requirements.txt"
script: xvfb-run -a py.test . --nomigrations -n 2 --cov="." --cov-report="term-missing" --isort
after_script: pip install coveralls && coveralls
