language: python
python:
  - "3.4"
  - "3.5"
  - "nightly"
env:
  - DJANGO_SETTINGS_MODULE=settings.test
  - DJANGO_EMAIL_HOST=not_used_in_tests
  - DJANGO_EMAIL_HOST_USER=not_used_in_tests
  - DJANGO_EMAIL_HOST_PASSWORD=not_used_in_tests
  - TWILIO_FROM_NUM=+15005550006
  - SLACK_URL=''
  - FROM_EMAIL=noreply@example.com
install: "pip install -r requirements.txt"
script: py.test . --nomigrations -n 2 --cov="." --cov-report="term-missing"
after_script: pip install coveralls && coveralls
