db:
  image: postgres
redis:
  image: redis
assets:
  build: ./apostello/assets/
  command: bash -c "npm install --quiet && npm run build"
  volumes:
    - .:/code
q:
  build: .
  environment:
    DJANGO_SETTINGS_MODULE: settings.docker
    REDIS_URL: redis://redis:6379
  command: ./manage.py qcluster
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
    - redis
web:
  build: .
  environment:
    DJANGO_SETTINGS_MODULE: settings.docker
  command: bash -c "sleep 3 && ./manage.py runserver 0.0.0.0:8000"
  volumes:
    - .:/code
  ports:
    - "4000:8000"
  links:
    - q 
    - db
    - redis
