version: '2'

volumes:
  postgres_data: {}

services:
  postgres:
    env_file: .env
    environment:
      - POSTGRES_USER=apostello
      - POSTGRES_PASSWORD=apostello
    image: postgres
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/backups/postgres:/backups
    restart: always
  redis:
    image: redis
    restart: always
  q:
    build: 
      context: .
      dockerfile: ./docker/django/Dockerfile
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=settings.docker_prod
    command: ./manage.py qcluster
    depends_on:
      - postgres
      - redis
    restart: always
  django:
    build: 
      context: .
      dockerfile: ./docker/django/Dockerfile
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=settings.docker_prod
    command: ./docker/django/gunicorn.sh
    depends_on:
      - postgres
      - redis
    restart: always
  caddy:
    build: 
      context: .
      dockerfile: ./docker/caddy/Dockerfile
    env_file: .env
    command: ./start_server.sh 
    volumes:
      - ./docker/backups/.caddy:/root/.caddy
      - ./static:/apostello/static
    ports: 
      - "443:443"
      - "80:80"
    depends_on:
      - django
    restart: always
