---

- name: Install packages required by the Django app inside virtualenv
  pip:
    requirements: "{{ requirements_file }}"
    executable: "{{ virtualenv_path }}/bin/pip"

- name: Run the Django migrate command
  command: '{{virtualenv_path}}/bin/python {{ application_path}}/manage.py migrate --settings={{ django_settings_file}}'
  when: run_django_migrate
  tags: django

- name: Run Django collectstatic
  command: '{{virtualenv_path}}/bin/python {{ application_path}}/manage.py collectstatic --noinput --settings={{ django_settings_file}}'
  when: run_django_collectstatic
  tags: django

- name: Setup clearsessions cron job
  cron: name="django {{application_name}} clearsessions"
        weekday="0"
        user="root"
        job="{{virtualenv_path}}/bin/python {{ application_path}}/manage.py clearsessions --settings={{ django_settings_file }}"
