---

- name: Create virtualenv folder
  file: path={{ virtualenv_path }} state=directory

- name: Create the virtualenv
  command: python3.7 -m venv "{{ virtualenv_path }}"
           creates={{ virtualenv_path }}/bin/activate

- name: Update pip and setuptools
  command: "{{ virtualenv_path }}/bin/pip install -U pip setuptools"

- name: Ensure gunicorn is installed
  command: "{{ virtualenv_path }}/bin/pip install gunicorn"

- name: Create the Gunicorn script file
  template: src=gunicorn_start.j2
            dest={{ virtualenv_path }}/bin/gunicorn_start
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0755
            backup=yes

- name: Create the application log folder
  file: path={{ application_log_dir }}
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        mode=0774
        state=directory

- name: Create the application log file
  file: path={{ application_log_file }} state=touch

- name: Create the virtualenv postactivate script to set environment variables
  template: src=virtualenv_postactivate.j2
            dest={{ virtualenv_path }}/bin/postactivate
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0640
            backup=yes

- name: Set permission to the application log file
  file: path={{ application_log_file }}
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        mode=0664
        state=file

- name: Create the maintenance page
  template: src=maintenance_off.html
            dest={{ virtualenv_path }}/maintenance_off.html
            mode=0664
