---

- name: Install Nginx
  apt: name=nginx-extras update_cache={{ update_apt_cache }} state=installed
  tags: packages

- name: Create the Nginx configuration file
  template: src=nginx.conf.j2
            dest=/etc/nginx/nginx.conf
            backup=yes
  notify: reload nginx

- name: Create the Nginx site configuration file
  template: src=nginx_site_config.j2
            dest=/etc/nginx/sites-available/{{ application_name }}
            backup=yes
  notify: reload nginx

- name: Ensure that the default site is disabled
  file: path=/etc/nginx/sites-enabled/default
        state=absent
  notify: reload nginx

- name: Ensure that the application site is enabled
  file: src=/etc/nginx/sites-available/{{ application_name }}
        path=/etc/nginx/sites-enabled/{{ application_name }}
        state=link
  notify: reload nginx

- name: Ensure Nginx service is started
  service: name=nginx state=started enabled=yes
