---

- name: Provision a {{ application_name }} server
  hosts: all
  become: yes
  become_user: root
  remote_user: root
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
    - setup_ufw: no
    - create_swap_file: no
    - run_django_migrate: yes
    - run_django_collectstatic: yes
    - setup_lets_encrypt: no
  vars_files:
    - env_vars/base.yml
    - env_vars/test.yml
  roles:
    - base
    - db
    - web
    - redis
    - djangoq
